language: node_js
node_js:
  - "0.10"
  - "0.12"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter

#travis build  speed up
sudo: false
cache:
  directories:
    - node_modules

script: grunt coverage
after_script: CODECLIMATE_REPO_TOKEN=397bd063807e728c91cf94873adede1dd2c0f220ba66078463d3c3f2d8aeb03d codeclimate-test-reporter < ./coverage/lcov.info
