language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

env:
  matrix:
    - SHOWDOWN_VERSION=1.2
    - SHOWDOWN_VERSION=1.3
    - SHOWDOWN_VERSION=1.4
    - SHOWDOWN_VERSION=1.5
    - SHOWDOWN_VERSION=1.6
  global:
    secure: nIjsfZ/tX5iGyapnRgO2bq9bmlWKu6hAF6yegRwCBOEQkZh60gneHqFK9nV7JryP5mWK3S0xCwlB4Oang2TE14GvRAsiEIj3DWb7sCZ/HYNbK/HKrWnB3ZnVinzv7oTGoYRc4J4iere7bETmJSLmEYG4J2IsxVc/ffQHSQ3gUr0n1mpEcLKwjvaKJhkEL59NVrYI9gOR8duGRgwr3/qipQsYvGhjuiaH/XyslFxdPSGz+WxWmQrigBXBml5IQkvEN4xVFxjjCTvYzfvtSQGW0hKGhp1/77w6ZWRjBdBnNOSyiWCu9y9cuCWyUTJmTMqEhHEnN2UVVVOwdnX6Xzr4UbsopA+zNUpRBQIIBx+1GimyHCrD1cZA2KtZOCqBAeQoTlyC7cMLmQpE5FFmbrwP19xi+6FLcAauCrRPs4oY77CSbgIS0jcs2ncCKJwvQBwM4aBs72AZQQ0cSBjMwLsC1Y5Syu35qKK/qpqhXyg5g7/xZLB6ixBJCbOEoLMEuAy3ZZJkhKz4+gQUocQojV5v8fIBC5w3lnq7q/Un4VpGW5EwkiGTciGvCmLwPZrg0GZwcENQBG2TcwMigFFxrvct9RF3DL3MrQbwC8Rx0Bsn3a4fof0/y4lWk/Mihx+4BJ2MFRM6ZD9dv8eg40RoyKIwgK0sOf0+1mLf0IPwB+s6tIc=

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter

install:
  - npm install
  - npm install showdown@${SHOWDOWN_VERSION}

sudo: false
cache:
  directories:
    - node_modules

script: grunt coverage
after_script: codeclimate-test-reporter < ./coverage/lcov.info

deploy:
  provider: npm
  email: ph.wolfer@gmail.com
  api_key:
    secure: Yo2KmdAvsJ56RH+Wj1iaiRVpBxFIBeD+3OQ5U5Ap3KozTYa5Mn90WWcXJSHKx/UgEzMgpY0qvN/WlBLRsV9R8akcd10XmpVP6f6wWTR6ZBoPa/OgEhlPyxtV1augEg4uc47W6JT/yXzfOsvpDsoNt6BzJPS/L7EDTaKjM+4RAkkTMQtHwk7LL1k+2P+xK+mJP3BchhjHkmP70QCPt8gD8uq7+R26to9JyBeMxGPTJU3/bTMyfuxAz9bWOu+jPMIVvbZmo+yYm7XZLF3CCxfm0VZn82o5lbSn52jBv/oSABx7eowMDJ83kJ7UCSF/rOAqtDMVI/6TUHBTJHtqZojzf3fQqcZBaggAAI7Yl8fx3dWeOXjegHz5IFJzlVQUeZcTGvcl0Ap284yY+lvwi7obqiroDbBwo9JoLDr76VyWLeiUI9NBoeylhmUHgu7zNQoWQ1Kv/9YQ18cq9QHYhyWVoeptnyRLZxESNx/fFgrhEk7R9z26+uydse4drZY/icl6zfU9jVyY7NrpBKEIrSOc9452DCu3e79StAWQB4w1hzP6/XFZlpbWgrm7ikJmu2U6wQjP85BsXLXrzFFz9qABjZhtGFhguVFlhYTSY1VO72H+8kBKeDn66qLm2OiZ6HhFGDwrdvM7uqu+BXH1X/DsJYsAMH9baGH1qbVoB9yFX00=
  on:
    branch: master
    tags: true
    node: "4"
    condition: "$SHOWDOWN_VERSION = 1.2"
